name: Maven Verify

on:
  push:
    branches:
      - '**'

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        run: |
          git clone ${{ gitea.server_url }}/${{ gitea.repository }} .
          git checkout ${{ gitea.sha }}
      
      - name: Set up JDK
        run: |
          apt-get update
          apt-get install -y openjdk-17-jdk maven
      
      - name: Run Maven verify
        run: mvn verify    
