name: Maven Verify

on:
  push:
    branches:
      - '**'

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        run: |
          git clone ${{ gitea.server_url }}/${{ gitea.repository }} .
          git checkout ${{ gitea.sha }}
          ls -lah .
