name: Maven Verify

on:
  push:
    branches:
      - '**'
jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9-eclipse-temurin-17
    
    steps:
      - name: Checkout code
        run: |
          git clone ${{ gitea.server_url }}/${{ gitea.repository }} .
          git checkout ${{ gitea.sha }}
      
      - name: Run Maven verify
        run: mvn verify
